import { db } from '@/lib/db';
import Link from 'next/link';

async function getDashboard() {
  try {
    const [customers, highIntent, activeCarts, abandonedCarts, failedPayments, emailsSent, approvals, tickets] = await Promise.all([
      db.customer.count(), db.intentAnalysis.count({ where: { intentType: 'PURCHASE_READY' } }), db.cart.count({ where: { status: 'OPEN' } }),
      db.cart.count({ where: { status: 'ABANDONED' } }), db.paymentAttempt.count({ where: { status: 'FAILED' } }), db.message.count({ where: { status: 'SENT' } }),
      db.recommendedAction.count({ where: { status: { in: ['PENDING', 'APPROVAL'] } } }), db.supportTicket.count({ where: { status: 'OPEN' } }),
    ]);
    return { customers, highIntent, activeCarts, abandonedCarts, failedPayments, emailsSent, approvals, tickets, connected: true };
  } catch { return { customers: 0, highIntent: 0, activeCarts: 0, abandonedCarts: 0, failedPayments: 0, emailsSent: 0, approvals: 0, tickets: 0, connected: false }; }
}

export default async function Home() {
  const data = await getDashboard();
  const cards = [['CUSTOMERS', data.customers], ['HIGH INTENT', data.highIntent], ['ACTIVE CARTS', data.activeCarts], ['ABANDONED CARTS', data.abandonedCarts], ['FAILED PAYMENTS', data.failedPayments], ['EMAILS SENT', data.emailsSent]];
  const navItems = ['Overview', 'Live Intent Feed', 'Customers', 'Customer 360', 'Carts & Checkout', 'Failed Sales', 'Email Center', 'Knowledge Base', 'Campaigns', 'Approvals', 'Audit Logs', 'Settings'];
  const destinations: Record<string, string> = { Customers: '/customers', 'Customer 360': '/customers', Approvals: '/approvals', 'Audit Logs': '/audit-logs', 'Knowledge Base': '/knowledge', Settings: '/settings' };
  return <main className="shell"><aside className="sidebar"><div className="brand"><span className="prompt">&gt;_</span><span>INTENTLOOP</span></div><p className="muted">REVENUE / INTELLIGENCE</p><nav>{navItems.map((item, index) => <Link className={index === 0 ? 'nav-active' : ''} href={destinations[item] ?? '/'} key={item}><span>{index === 0 ? '●' : '○'}</span>{item}</Link>)}</nav><div className="system"><span className={data.connected ? 'dot green' : 'dot red'} />{data.connected ? 'DATABASE ONLINE' : 'DATABASE OFFLINE'}<small>v0.1.0 / LOCAL</small></div></aside><section className="content"><header><div><p className="eyebrow">OPERATIONS / OVERVIEW</p><h1>Mission control</h1><p className="muted">Customer intent, conversion and retention in one loop.</p></div><div className="header-actions"><Link className="command" href="/customers">/ <span>Open customer search</span></Link><div className="avatar">DA</div></div></header>{!data.connected && <div className="notice"><span>!</span><div><strong>Database not configured</strong><p>Run <code>npm run db:push</code> to initialize local storage. Metrics remain honest at zero until data exists.</p></div></div>}<div className="toolbar"><div className="tabs"><button className="tab-active">Today</button><button>7 days</button><button>30 days</button></div><span className="updated">● LIVE · just now</span></div><div className="metrics">{cards.map(([label, value]) => <div className="metric" key={label}><span className="metric-label">{label}</span><strong>{value}</strong><small>{data.connected ? 'FROM DATABASE' : 'NO DATA'}</small></div>)}</div><div className="grid"><section className="panel"><div className="panel-head"><div><p className="eyebrow">CONVERSION PATH</p><h2>Lifecycle funnel</h2></div><span className="tag cyan">LIVE</span></div>{[['Visitors', 0], ['Identified leads', data.customers], ['High intent', data.highIntent], ['Checkout started', data.activeCarts + data.abandonedCarts], ['Converted', 0]].map(([label, value]) => <div className="funnel-row" key={label}><span>{label}</span><div className="bar"><i style={{ width: `${Math.min(100, Number(value) * 10)}%` }} /></div><b>{value}</b></div>)}</section><section className="panel"><div className="panel-head"><div><p className="eyebrow">ACTION QUEUE</p><h2>Needs attention</h2></div><span className="tag amber">LIVE</span></div><div className="queue-stats"><div><strong>{data.approvals}</strong><span>awaiting approval</span></div><div><strong>{data.tickets}</strong><span>open tickets</span></div><div><strong>{data.emailsSent}</strong><span>messages sent</span></div></div><div className="empty"><span>∅</span><p>Actions are created from customer context and policy checks.</p></div></section></div></section></main>;
}
